### ISSUE TITLE
Type stability of eigen

### ISSUE THREAD

**Issue by ChenNingCong** [adknudson/NearestCorrelationMatrix.jl#3]
It's a well-known issue that `eigen` return a union of complex matrix and real matrix. It seems that your code assumes that the return value is always a real matrix. To prevent type instability, consider replacing all the `eigen` with following function:
```
function realeigen(x::Matrix{T})::Pair{Vector{T}, Matrix{T}} where T <: AbstractFloat
    (v, M) = eigen(x)
    return v=>M
end
```
This type instability is detected by [SimpleTypeChecker.jl](https://github.com/ChenNingCong/SimpleTypeChecker), a type checker to enforce Fortran-style programming.

**Comment by adknudson** [comment]
Thanks for the tip! I'll look into this shortly, but it may not be an issue. The eigen decomposition is always called on a real symmetric matrix, so the eigenvalues and vectors will also always be real.

See https://discourse.julialang.org/t/eigen-warntype/21239/4

**Comment by ChenNingCong** [comment]
> The eigen decomposition is always called on a real symmetric matrix

Then you should use `eigen(LinearAlgebra.Symmetric(x))` to ensure type stable result.

> I'll look into this shortly, but it may not be an issue. The eigen decomposition is always called on a real symmetric matrix, so the eigenvalues and vectors will also always be real.

Unfortunately, this is not how Julia's type inferencer works. Because it's impossible for it to know whether a matrix is a real symmertric one (such reasoning might be too hard), so it always returns a union. (It's common that inferred type is larger than actual runtime). This union can pollute all the codes following `eigen`.

**Comment by adknudson** [comment]
Calling `Symmetric(x)` seems to have negligible overhead, so I will replace calls to `eigen(x)` with `eigen(Symmetric(x))`. I'll mark this issue as closed, and you should see the change in the next patch release.
